### ISSUE TITLE
 مشکل اساسی در فایل های کلش جنریت شده

### ISSUE THREAD

**Issue by Gherkashen2** [Incognito-Coder/SurfSocks#1]
در فایل های جنریت شده ی کلش دی ان اس زیر از 
https://dnsforge.de/dns-quer
به
https://dnsforge.de/dns-query 
باید تصحیح گردد. 
با سپاس

**Comment by Incognito-Coder** [comment]
> در فایل های جنریت شده ی کلش دی ان اس زیر از 
> 
> https://dnsforge.de/dns-quer
> 
> به
> 
> https://dnsforge.de/dns-query 
> 
> باید تصحیح گردد. 
> 
> با سپاس

با تشکر از اطلاع رسانی،حتما اصلاح میگردد.

**Comment by Gherkashen2** [comment]
سپاس
Here's List of Malware, Phishing, ADS & Tracker websites (Only GEO IR) for Adding in Clash subscription URL :
:لیست سایت های تبلیغاتی و فیشینگ فارسی جهت مسدودسازی در کلش
https://github.com/Shikopat/block/blob/main/block.yml

**Comment by Gherkashen2** [comment]
لطفا
GEOIP:IR,DIRECT
را نیز به بخش رول ها اضافه کنید

**Comment by Incognito-Coder** [comment]
solved.
