### ISSUE TITLE
ابهام در NAMESERVER

### ISSUE THREAD

**Issue by Shikopat** [Incognito-Coder/SurfSocks#3]
درود
علت استفاده از دی ان اس 
151.236.14.64
در بخش nameserver 
چیست؟
و چرا از دی ان اس های معتبر 
ZERO LOGGING 
استفاده نمی کنین؟
هیچ اطلاعاتی از دی ان اس فوق و حریم خصوصی ان وجود ندارد

https://scamalytics.com/ip/151.236.14.64
گزارش فوق را نیز ببینید!

**Comment by Incognito-Coder** [comment]
این DNS برای خود سرفشارک هست و فقط برای کانفیگ ها این شرکت قابل استفادست (یکی از DNS های که  دیفالت در اپ سرفشارک استفاده میشه)
